version: '3.1'

services:
     jenkins:
     image: jenkins/jenkins
     container_name: jenkins
     restart: always
     hostname: jenkins
     ports:
         - 8080:8080

     grafana:
           image: grafana/grafana
           container_name: grafana
           restart: always
           hostname: grafana
           ports:
            - 3000:3000

